Repository GSG-CF05/CryptocurrencySite, pull requests merged in 2022-03, with the labels that each got.

#2 create folders for cryptocurrency site relate #1
  About/about.css
  About/about.html
  About/about.js
  Contact Us/contact.css
  Contact Us/contact.html
  Contact Us/contact.js
  Cryptocurrency/crypto.css
  Cryptocurrency/crypto.html
  Cryptocurrency/crypto.js
  index.html
  main.js
  style.css
Labels: approved

#10 upload images for this project relate #8
  images/analysis.svg
  images/bitcoin.png
  images/bitcoinImg.jpg
  images/contact_us.svg
  images/cripto.jpg
  images/crypto.jpg
  images/crypto2.jpg
  images/crypto3.jpg
  images/crypto4.jpg
  images/dollar.png
  images/email.svg
  images/evolution-of-retail-analytics-190318.jpg
  images/info-what-is-crypto-04.jpg
  images/like-svgrepo-com.svg
  images/logo-light.png
  images/phone-svgrepo-com.svg
  images/undraw_dashboard_re_3b76.svg
  images/undraw_nakamoto_-2-iv6.svg
  images/volume-control.png
  images/world-svgrepo-com.svg
Labels: witting Review

#15 created html css js code for layout project pages + made some edits t…
  css/all.css
  css/media.css
  css/style.css
  fonts/Poppins/Poppins-Medium.ttf
  fonts/Poppins/Poppins-Regular.ttf
  fonts/Poppins/Poppins-SemiBold.ttf
  index.html
  main.js
  style.css
Labels: waiting-review

#17 adding dark mode js file and deleting all css file in my project
  css/all.css
  index.html
  js/dark.js
  js/main.js
Labels: done

#19 Create main home
  css/style.css
  images/market-banner.jpg
  index.html
Labels: waiting-review

#18 create main about us relates #5
  About/about.css
  About/about.html
Labels: in Progress, 3HT

#21 7 creat main contactus page
  Contact Us/contact.css
  Contact Us/contact.html
Labels: awaiting-review

#31 created all content of readme file, explaing all details about the we…
  README.md
Labels: awaiting-review

#30 edit about page relate #29
  About/about.css
  About/about.html
Labels: awaiting-review

#32 6 create main market page
  .vscode/settings.json
  Cryptocurrency/crypto.html
  Cryptocurrency/crypto.js
  Market/market.css
  Market/market.html
  Market/market.js
Labels: approved

#37 Top 20 market cap coins is now rea, i, first build the Box Dom functi…
  Market/market.html
  Market/market.js
Labels: waiting-review

#38 made the top 5 gainers & losers function, but needs to be debugged ag…
  Market/market.js
Labels: awaiting-review
